# Generated by Django 5.1 on 2025-05-31 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChequeProcesado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuit', models.CharField(max_length=20)),
                ('numero_cheque', models.CharField(max_length=20)),
                ('codigo_entidad', models.CharField(max_length=10)),
                ('resultado_denunciado', models.JSONField()),
                ('resultado_rechazados', models.JSONField()),
                ('resultado_deudas', models.JSONField()),
                ('fecha_procesado', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
