# Generated by Django 5.1 on 2025-08-04 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheques', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chequeprocesado',
            old_name='fecha_procesado',
            new_name='creado',
        ),
        migrations.RemoveField(
            model_name='chequeprocesado',
            name='resultado_denunciado',
        ),
        migrations.RemoveField(
            model_name='chequeprocesado',
            name='resultado_deudas',
        ),
        migrations.RemoveField(
            model_name='chequeprocesado',
            name='resultado_rechazados',
        ),
        migrations.RemoveField(
            model_name='chequeprocesado',
            name='usuario',
        ),
        migrations.AddField(
            model_name='chequeprocesado',
            name='datos_denunciado',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chequeprocesado',
            name='datos_deudas',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chequeprocesado',
            name='datos_rechazado',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chequeprocesado',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='cheques/'),
        ),
        migrations.AlterField(
            model_name='chequeprocesado',
            name='codigo_entidad',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='chequeprocesado',
            name='numero_cheque',
            field=models.CharField(max_length=30),
        ),
    ]
